### ISSUE TITLE
Runtime error: "Index out of range"                                           

### ISSUE THREAD

**Issue by kingy000** [jsqw/SRL-neon#1]
Succesfully compiled in 1422 milliseconds.
[00:00:00:359]:[RSClient]: Client mode changed: FIXED
[00:01:24:984]:[MM2MS]: Unknown zoom level, reading from options...
[00:01:32:531]:[MM2MS]: Current zoom level: -1
Runtime error: "Index out of range (index:-1, low:0, high:100)" at line 63, column 30 in file "C:\Users\Possy\AppData\Local\Simba\Includes\SRL-T\osr\mm2ms_projector.simba"

**Comment by kingy000** [comment]
for camdozaalfisher

**Comment by jsqw** [comment]
w

**Comment by jsqw** [comment]
Hey, do you have the RuneLite "Camera" plugin enabled and the Zoom extended?

**Comment by jsqw** [comment]
People have had this issue with JLauncher.

**Comment by jsqw** [comment]
> > Hey, do you have the RuneLite "Camera" plugin enabled and the Zoom extended?
> 
> this one work. tyvm! I dont use Jlaunch.

Good to hear.
