### ISSUE TITLE
keep spinning

### ISSUE THREAD

**Issue by kingy000** [jsqw/SRL-neon#2]
[00:03:43:328]:[Antiban]: Random Right Click   

keep spinning long time

**Comment by jsqw** [comment]
> [00:03:43:328]:[Antiban]: Random Right Click
> 
> keep spinning long time

Which script are you using? Could you give me a screenshot when this occurs?

**Comment by kingy000** [comment]
camdozaalfisher

**Comment by jsqw** [comment]
> camdozaalfisher

Off the top of my head:
- Make sure that your brightness is set to max
- Restart runelite
- Make sure that the plugin is loaded with correct settings

**Comment by ruffstuffgaming** [comment]
Same issue here with the MTA scripts. 
![2023-10-30 13_52_00-NVIDIA GeForce Overlay](https://github.com/jsqw/SRL-neon/assets/149427492/8e134c7f-9a98-4851-881d-4b54e9539877)
Here is a screenshot of what is seen. Let me know if you need a screenshot of anything else.

What I've done to setup the script:
1. Ran script to get MTA.properties file
2. Imported file into RuneLite and ensured my profile is set to the imported one
3. Set brightness to max
4. Target the game with Simba
5. Equip air staff and law runes for telekinesis room, and start script

What I've done to attempt to fix the issue (restarting RuneLite and trying again after each step):
1. Reinstall RuneLite 32-bit
2. Update SRL-T and WaspLib
3. Re-import the MTA.properties file
4. Disable all plugins within the imported profile
5. Run Simba as administrator

It's also worth mentioning that RuneLite does not seem to be displaying any colors in-game as it usually would with the MTA plugin. I think I see references in the code to "GreenMarker" and similar things, but the game does not show any markers.
I would imagine this is a profile issue, but would love to hear your thoughts. :)

**Comment by kingy000** [comment]
![IMG_9676](https://github.com/jsqw/SRL-neon/assets/38481599/e79a2b07-f2a7-4622-b694-46b4f3de67ae)
My character would go to this location and just keep spinning.

**Comment by kingy000** [comment]
I haven’t try run as administrator yet

**Comment by ruffstuffgaming** [comment]
My issue has been resolved. The issue was indeed with the profile. The MTA.properties that was being created in \Simba\MTA did not have the correct RuneLite profile properties. I had to import the one packaged in \SRL-neon-main\mta\mta.properties, which did have the correct profile properties.

I believe this means that the MTA script is not properly generating the MTA.properties file. However, since the file is included in the package anyways, updating the instructions with the file path of that file is probably fine.

@kingy000, it looks like CamdozaalFisher has a profile located in \SRL-neon-main\camdozaalfisher\cf.properties. Can you try importing that profile into your RuneLite and see if it works for you?

**Comment by jsqw** [comment]
> My issue has been resolved. The issue was indeed with the profile. The MTA.properties that was being created in \Simba\MTA did not have the correct RuneLite profile properties. I had to import the one packaged in \SRL-neon-main\mta\mta.properties, which did have the correct profile properties.
> 
> I believe this means that the MTA script is not properly generating the MTA.properties file. However, since the file is included in the package anyways, updating the instructions with the file path of that file is probably fine.
> 
> @kingy000, it looks like CamdozaalFisher has a profile located in \SRL-neon-main\camdozaalfisher\cf.properties. Can you try importing that profile into your RuneLite and see if it works for you?

Good to hear that you got it working. I will probably record a video on how to setup a fresh RuneLite install when I have the time. Simba can be picky.

**Comment by kingy000** [comment]
![ffggfgvgh](https://github.com/jsqw/SRL-neon/assets/38481599/ab365d5b-6d82-45e3-b276-68892b3f72e0)

i got this?

**Comment by kingy000** [comment]
a lot of tims

**Comment by jsqw** [comment]
> a lot of tims

What @ruffstuffgaming said. RemoteInput was built for the vanilla client and will bug out if you modify the client window by messing with the RuneLite sidebar. You should hide it and restart Simba and RuneLite.

**Comment by kingy000** [comment]
Thanks I will give this a try. 
but my camera still keeps spinning. I noticed that it keeps stopping at the location that I took screenshots on my previous post. When that happens I click in cooking and prayer room and it stops spinning. It’s almost as it’s struggling to find the room.

**Comment by kingy000** [comment]
https://drive.google.com/file/d/1k30ueaYNiBD5_pAgzRfHn-9_M5Bc2t_R/view?usp=sharing

Video of  what i been telling you.

**Comment by jsqw** [comment]
> https://drive.google.com/file/d/1k30ueaYNiBD5_pAgzRfHn-9_M5Bc2t_R/view?usp=sharing
> 
> Video of what i been telling you.

That's weird.. Do you have the newest version?
Anyhow, it might be some weird heightmap thing in SRL.
Try changing this line (216):   
TableLocation: TPoint := [1108, 3970]; 
to:
TableLocation: TPoint := [1112, 3970];

**Comment by kingy000** [comment]
It worked!!!! 
thank you very much for your help.
You don’t know how helpful this script is for Ironman 
God bless you
